### ISSUE TITLE
possible missing dereference of key_buf_link in wrap_key

### ISSUE THREAD

**Issue by jimsingh** [bentonstark/libhsm#1]
I could be wrong here, but did you intend to dereference key_buf_len before the comparison?

https://github.com/bentonstark/libhsm/blob/a0b4050f5e35d9f6579a5e5e9ea003d0cc0dd528/src/p11hsm.cpp#L3425

**Comment by bentonstark** [comment]
You are not wrong.  On line 3425 that you referenced it should be fine since key_buf_len is being passed by value and does not need to be de-referenced.  But on line 3326 which I think is the one you are talking about since it is in the wrap_key function it is not OK.  It should be de-referenced before evaluating.   Most likely it was introduced via copy/paste.

https://github.com/bentonstark/libhsm/blob/a0b4050f5e35d9f6579a5e5e9ea003d0cc0dd528/src/p11hsm.cpp#L3326

**Comment by bentonstark** [comment]
fixed

https://github.com/bentonstark/libhsm/commit/6c54d21fa44f98faa84e25c055c2c3ec38250c7a
